# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - method: pip
      packages:
        - sphinx
        - myst-parser
        - sphinx-rtd-theme

