# .readthedocs.yaml
version: 2

# Define the build system
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Python environment setup
python:
  install:
    - method: pip
      path: .
    - method: pip
      packages:
        - sphinx
        - myst-parser
        - sphinx-rtd-theme

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

