# .readthedocs.yaml
version: 1

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

